### ISSUE TITLE
Access through noSuchMethod() does not work with minification

### ISSUE THREAD

**Issue by marcojakob** [chrisbu/dartwatch-JsonObject#23]
If I understand minification correctly, the following sample will not work:

```
var person = new JsonObject.fromJsonString('{"name":"Chris"}');
print(person.name); // will not work if 'name' is minified
```

A solution might be to use the new `Symbol` class, see [Goodbye InvocationMirror, Hello Invocation and Symbol](http://news.dartlang.org/2013/04/goodbye-invocationmirror-hello.html)

(btw: Thanks for the work and your great book about Dart!)

**Comment by stevenroose** [comment]
Is this fixed?
