### ISSUE TITLE
type 'Symbol' is not a subtype of type 'String' of 'key'.

### ISSUE THREAD

**Issue by marcog83** [chrisbu/dartwatch-JsonObject#27]
Hi, 
I updated dart editor
Dart Editor version 0.5.3_r22223
Dart SDK version 0.5.3.0_r22223

json_object version 1.0.15+1

and now when i parse json with JsonObject library an error occours
type 'Symbol' is not a subtype of type 'String' of 'key'.

thanks a lot
marco

**Comment by stevenroose** [comment]
Is the error still present? Can you point to the line in the json_object code that produces the error?
