### ISSUE TITLE
Test fails for dart 1.2

### ISSUE THREAD

**Issue by beatgammit** [chrisbu/dartwatch-JsonObject#37]
Here's the test results on my machine (Linux x64, dart-sdk 1.2):

    unittest-suite-wait-for-done
    testSampleData
    [{"chapter1":"Introduction to Dart","pages":["page1","page2","page3"]}, {"chapter2":"Dart tools"}]
    testStrongTyping
    Not found: wibble
    IsGetter: true
    IsSetter: true
    isAccessor: true
    testJsonStringify
    testIsExtendable
    {"name":"Mike"}
    {"id":"99-plural-z-alpha", "title":"Make way for new hyperspace bypass", "completed":false}
    PASS: sample data
    PASS: strong typing new
    PASS: strong typing from json string
    PASS: json stringify
    PASS: is extendable
    PASS: extend object
    PASS: toString
    PASS: dartlang article fromJson
    PASS: dartlang article new
    PASS: toTodoVO
    ERROR: list
      Test failed: Caught Bad state: Not allowed when tests are running.
      package:unittest/unittest.dart 646:5        _requireNotRunning
      package:unittest/unittest.dart 244:21       test
      test_list.dart 6:7                          testList
      json_object_test.dart 76:14                 main.<fn>
      package:unittest/src/test_case.dart 102:27  _run.<fn>
      dart:async/zone.dart 717                    _rootRunUnary
      dart:async/zone.dart 449                    _ZoneDelegate.runUnary
      dart:async/zone.dart 654                    _CustomizedZone.runUnary
      dart:async/future_impl.dart 439             _Future._propagateToListeners.handleValueCallback
      dart:async/future_impl.dart 522             _Future._propagateToListeners
      dart:async/future_impl.dart 303             _Future._complete
      dart:async/future_impl.dart 354             _Future._asyncComplete.<fn>
      dart:async/zone.dart 710                    _rootRun
      dart:async/zone.dart 440                    _ZoneDelegate.run
      dart:async/zone.dart 650                    _CustomizedZone.run
      dart:async/zone.dart 561                    _BaseZone.runGuarded
      dart:async/zone.dart 586                    _BaseZone.bindCallback.<fn>
      dart:async/schedule_microtask.dart 23       _asyncRunCallbackLoop
      dart:async/schedule_microtask.dart 32       _asyncRunCallback
      dart:isolate-patch/isolate_patch.dart 119   _RawReceivePortImpl._handleMessage
    PASS: list seralization

    11 PASSED, 0 FAILED, 1 ERRORS
    Unhandled exception:
    Exception: Some tests failed.
    #0      SimpleConfiguration.onDone (package:unittest/src/simple_configuration.dart:189:9)
    #1      _completeTests (package:unittest/unittest.dart:571:17)
    #2      _runTest (package:unittest/unittest.dart:520:19)
    #3      _nextTestCase (package:unittest/unittest.dart:450:11)
    #4      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
    #5      _asyncRunCallback (dart:async/schedule_microtask.dart:32)
    #6      _asyncRunCallback (dart:async/schedule_microtask.dart:36)
    #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:119)

**Comment by stevenroose** [comment]
Fixed in https://github.com/chrisbu/dartwatch-JsonObject/commit/c0fa761e0a7df490fb670ad665f80eaa63e0d528
