### ISSUE TITLE
Compatibility with flutter

### ISSUE THREAD

**Issue by ROTGP** [chrisbu/dartwatch-JsonObject#42]
I'm new to dart & [flutter](https://flutter.io/), but from what I understand your lib can't be used in flutter because it uses mirrors? Would a flutter-friendly branch be complicated? I'm sure there would be a large audience.  I tried removing references to mirror in your code but couldn't even get past the class declaration with the following error 
`Inconsistent declarations of 'cast' are inherited from <RV,RV>() [] Map <RV,RV>, <R>() [] Iterable<R>`

**Comment by stevenroose** [comment]
@b354c502 This package is not compatible with Strong Mode, which is default in Dart 2.0 and thus also in the new version of Flutter. As such, I would advise against using this package in the future. You can use the regular `JSON.decode()` from the `dart:convert` package.

**Comment by ROTGP** [comment]
@stevenroose that's a shame, but thanks for the quick clarification
