### ISSUE TITLE
Example at http://www.dartlang.org/articles/json-web-service/ throws exception in checked mode

### ISSUE THREAD

**Issue by bgourlie** [chrisbu/dartwatch-JsonObject#9]
The example at http://www.dartlang.org/articles/json-web-service/ says the following is valid:

    interface LanguageWebsite extends JsonObject { 
      String homepage;
      String api;
    }

    interface Language extends JsonObject {
      String language;
      List<String> targets;
      LanguageWebsite website;
    }

    Language data = new JsonObject.fromJsonString(req.responseText);

I found that this will cause dart to throw the following exception: `type 'JsonObject' is not a subtype of type 'Language' of 'data'.`

The way to make it work is to create an interface with a default implementation, and the default implementation extends JsonObject, which has a factory method that calls the following:
`return new JsonObject.fromJsonString(jsonString, new _LanguageImpl());`

I found the working solution in the unit tests.  I assume the example on the website needs to be updated.

**Comment by stevenroose** [comment]
Seems to be fixed :)
